[directory]
truncation_length = 5
format = " [$path]($style)[$lock_symbol]($lock_style) "

[hostname]
ssh_only = false
format = "[$hostname]($style)"
trim_at = "-"
style = "bold green"
disabled = false

[username]
style_user = "bold blue"
show_always = true

[vagrant]
format = "via [⍱ $version](bold white) "
